import { prisma } from '../src/prisma/index'

const inventarioCloud = [
  {
    tenant: 'Grupo Almo ES',
    nube: 'AWS',
    instanceName: 'prod-web-server-1',
    ipPublica: '52.15.123.45',
    ipPrivada: '10.0.1.10',
    instanceType: 't3.medium',
    cpu: 2,
    ram: '4GB',
    storageGib: '80GB',
    sistemaOperativo: 'Ubuntu 22.04 LTS',
    costoUsd: '45.00',
    hostName: 'prod-web-01',
    responsable: 'Juan Pérez',
    modoUso: 'Producción',
    service: 'EC2',
    antivirus: 'Ninguno',
  },
  {
    tenant: 'Grupo Almo ES',
    nube: 'AWS',
    instanceName: 'prod-db-server-1',
    ipPublica: '52.15.123.46',
    ipPrivada: '10.0.1.20',
    instanceType: 't3.large',
    cpu: 2,
    ram: '8GB',
    storageGib: '100GB',
    sistemaOperativo: 'Ubuntu 22.04 LTS',
    costoUsd: '85.00',
    hostName: 'prod-db-01',
    responsable: 'María García',
    modoUso: 'Producción',
    service: 'RDS PostgreSQL',
    antivirus: 'Ninguno',
  },
  {
    tenant: 'Grupo Almo MX',
    nube: 'Azure',
    instanceName: 'app-server-mx-01',
    ipPublica: '40.117.45.123',
    ipPrivada: '10.1.1.10',
    instanceType: 'Standard_D2s_v3',
    cpu: 2,
    ram: '8GB',
    storageGib: '50GB',
    sistemaOperativo: 'Windows Server 2019',
    costoUsd: '75.00',
    hostName: 'app-mx-01',
    responsable: 'Carlos López',
    modoUso: 'Producción',
    service: 'Virtual Machine',
    antivirus: 'Windows Defender',
  },
  {
    tenant: 'Grupo Almo ES',
    nube: 'AWS',
    instanceName: 'backup-s3-bucket',
    ipPublica: '',
    ipPrivada: '',
    instanceType: 'S3 Standard',
    cpu: 0,
    ram: '0GB',
    storageGib: '500GB',
    sistemaOperativo: '',
    costoUsd: '25.00',
    hostName: 'backup-bucket',
    responsable: 'Juan Pérez',
    modoUso: 'Almacenamiento',
    service: 'S3',
    antivirus: 'N/A',
  },
  {
    tenant: 'Grupo Almo CO',
    nube: 'GCP',
    instanceName: 'dev-server-co-01',
    ipPublica: '34.123.45.67',
    ipPrivada: '10.2.1.10',
    instanceType: 'e2-medium',
    cpu: 2,
    ram: '4GB',
    storageGib: '40GB',
    sistemaOperativo: 'Ubuntu 22.04 LTS',
    costoUsd: '35.00',
    hostName: 'dev-co-01',
    responsable: 'Ana Martínez',
    modoUso: 'Desarrollo',
    service: 'Compute Engine',
    antivirus: 'Ninguno',
  },
  {
    tenant: 'Grupo Almo ES',
    nube: 'AWS',
    instanceName: 'mail-server-1',
    ipPublica: '52.15.123.47',
    ipPrivada: '10.0.1.30',
    instanceType: 't3.small',
    cpu: 1,
    ram: '2GB',
    storageGib: '30GB',
    sistemaOperativo: 'Ubuntu 22.04 LTS',
    costoUsd: '25.00',
    hostName: 'mail-01',
    responsable: 'Laura Rodríguez',
    modoUso: 'Producción',
    service: 'EC2',
    antivirus: 'ESET Endpoint',
  },
  {
    tenant: 'Grupo Almo MX',
    nube: 'Azure',
    instanceName: 'files-storage-mx',
    ipPublica: '',
    ipPrivada: '',
    instanceType: 'Standard_LRS',
    cpu: 0,
    ram: '0GB',
    storageGib: '1000GB',
    sistemaOperativo: '',
    costoUsd: '50.00',
    hostName: 'files-mx',
    responsable: 'Carlos López',
    modoUso: 'Almacenamiento',
    service: 'Blob Storage',
    antivirus: 'N/A',
  },
  {
    tenant: 'Grupo Almo ES',
    nube: 'AWS',
    instanceName: 'monitoring-server',
    ipPublica: '52.15.123.48',
    ipPrivada: '10.0.1.40',
    instanceType: 't3.small',
    cpu: 1,
    ram: '2GB',
    storageGib: '20GB',
    sistemaOperativo: 'Ubuntu 22.04 LTS',
    costoUsd: '20.00',
    hostName: 'monitor-01',
    responsable: 'Juan Pérez',
    modoUso: 'Monitorización',
    service: 'EC2',
    antivirus: 'Ninguno',
  },
  {
    tenant: 'Grupo Almo ES',
    nube: 'AWS',
    instanceName: 'prod-load-balancer',
    ipPublica: '52.15.123.49',
    ipPrivada: '10.0.1.5',
    instanceType: 'application-load-balancer',
    cpu: 0,
    ram: '0GB',
    storageGib: '0GB',
    sistemaOperativo: '',
    costoUsd: '30.00',
    hostName: 'alb-prod',
    responsable: 'Juan Pérez',
    modoUso: 'Producción',
    service: 'ALB',
    antivirus: 'N/A',
  },
  {
    tenant: 'Grupo Almo CO',
    nube: 'GCP',
    instanceName: 'cloud-sql-co-01',
    ipPublica: '34.123.45.68',
    ipPrivada: '10.2.1.20',
    instanceType: 'db-f1-micro',
    cpu: 1,
    ram: '0.6GB',
    storageGib: '10GB',
    sistemaOperativo: 'PostgreSQL 14',
    costoUsd: '15.00',
    hostName: 'sql-co-01',
    responsable: 'Ana Martínez',
    modoUso: 'Producción',
    service: 'Cloud SQL',
    antivirus: 'N/A',
  },
]

async function seedInventarioCloud() {
  console.log('🔄 Injectando datos de inventario cloud...\n')

  try {
    for (const item of inventarioCloud) {
      const existente = await prisma.inventarioCloud.findFirst({ where: { instanceName: item.instanceName } })
      if (!existente) {
        await prisma.inventarioCloud.create({ data: item })
        console.log(`  ✅ Creado: ${item.instanceName} (${item.nube})`)
      } else {
        console.log(`  ⏭️  Ya existe: ${item.instanceName}`)
      }
    }

    console.log('\n✅ Inventario cloud injectado correctamente!')
  } catch (error) {
    console.error('\n❌ Error:', error)
  } finally {
    await prisma.$disconnect()
  }
}

seedInventarioCloud()
